tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "coreutils"
brew "deno"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "hub"
brew "imagemagick"
brew "mas"
brew "peco"
brew "pngquant"
brew "tig"
brew "zsh"
cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "boostnote"
cask "discord"
cask "docker"
cask "figma"
cask "firefox"
cask "fork"
cask "franz"
cask "iterm2"
cask "jetbrains-toolbox"
cask "kindle"
cask "scroll-reverser"
cask "sequel-ace"
cask "slack"
cask "visual-studio-code"
cask "zeplin"
cask "zoom"
mas "BetterSnapTool", id: 417375580
mas "LINE", id: 539883307
mas "Paste", id: 967805235
mas "ScreenPointer", id: 1368204906
mas "Xcode", id: 497799835
